name: Docker test

on: [push, pull_requests]
jobs:
        build:
                runs-on: ubuntu-latest
                container: 
                        image: quay.io/fenicsproject/stable:current
                steps:
                        name: Test with pytest
                run:
                        python3 -m pytest

